### ISSUE TITLE
Need parser for SyGuS V1

### ISSUE THREAD

**Issue by abhishekudupa** [SyGuS-Org/tools#1]
Currently, the parser only supports SyGuS v2. The community needs a parser for SyGuS v1 as well. This should be fairly straightforward, but requires some amount of work.

**Comment by SaswatPadhi** [comment]
Hi Abhishek.

Do we have the sources for the parsers that are already being used on StarExec to check the submitted benchmarks?
Given that we are deprecating SyGuS-IF v1, it would be better if we could reuse those and fix any existing bugs, instead of writing one from scratch.

**Comment by abhishekudupa** [comment]
@SaswatPadhi We do have the sources. As I've mentioned elsewhere, I tried to reuse that parser to build the v2 parser. Many thousands of lines of C++ later, the end was nowhere in sight :-( Which is why I decided to rewrite in Python. Also, the old C++ parser had numerous issues that were being worked around: for example, it didn't support chainable and associative operators which could take an arbitrary number of arguments (`(+ t1 t2 t3 ...)`). All of these issues have been resolved in the v2 parser.

I think a large part of the code can be shared between the v2 and the v1 parser. I think that building a v1 parser on top of the v2 parser can be done with a few hundreds of lines of Python more.

**Comment by abhishekudupa** [comment]
@SaswatPadhi Another reason to build a v1 parser on top of the new v2 parser is that we'll need to write a translator to convert v1 <==> v2. This might be easier in Python than in C++ (even considering the overhead to rewrite the v1 parser in Python)

**Comment by SaswatPadhi** [comment]
Thanks @abhishekudupa. I see your point.

Even if we reuse the old parser, we would still need the translator you mentioned, so I agree that it makes sense to add support to our v2 parser.

**Comment by abhishekudupa** [comment]
This issue is resolved.
